# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    web.vm.network "private_network", ip: "192.168.3.10"
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 php libapache2-mod-php php-mysql php-curl

      # Change VM's webserver's configuration to use shared folder.
      # (Look inside test-website.conf for specifics.)
      cp /vagrant/frontend.conf /etc/apache2/sites-available/
      # activate our website configuration ...
      a2ensite frontend
      # ... and disable the default website provided with Apache
      a2dissite 000-default
      # Reload the webserver configuration, to pick up our changes
      service apache2 reload
    SHELL
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "private_network", ip: "192.168.3.11"
    mysql.vm.provision "shell", inline: <<-SHELL
      apt-get update

        export MYSQL_PWD='insecure_mysqlroot_pw'

        echo "mysql-server mysql-server/root_password password $MYSQL_PWD" | debconf-set-selections
        echo "mysql-server mysql-server/root_password_again password $MYSQL_PWD" | debconf-set-selections

        apt-get -y install mysql-server

        echo "CREATE DATABASE josidrive;" | mysql
        echo "CREATE USER 'webuser'@'%' IDENTIFIED BY 'insecure_db_pw';" | mysql
        echo "GRANT SELECT, INSERT ON josidrive.* TO 'webuser'@'%';" | mysql

        echo "CREATE USER 'admin'@'%' IDENTIFIED BY 'secure_db_pw';" | mysql
        echo "GRANT ALL PRIVILEGES ON josidrive.* TO 'admin'@'%';" | mysql

        export MYSQL_PWD='secure_db_pw'

        cat /vagrant/setup-database.sql | mysql -u admin josidrive

        sed -i'' -e '/bind-address/s/127.0.0.1/0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf

        service mysql restart
    SHELL
  end

end
